version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.1.0-a3e9bd9
    restart: on-failure:0
    ports:
     - "8080:8080"
    environment:
      LOG_LEVEL: "debug"
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
  t2v-transformers:
    image: semitechnologies/transformers-inference:distilbert-base-uncased
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]      
    environment:
      ENABLE_CUDA: 1
